import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Gnb from '@/components/layout/Gnb';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='h-screen grid grid-rows-[auto_1fr_auto]'>
          <Gnb />
          <main className='p-8'>{children}</main>
          <footer className='text-center text-gray-500 dark:text-gray-400 text-sm py-4'>
            © {new Date().getFullYear()} Stock Manager. All rights reserved.
          </footer>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
